#!/bin/bash

#SBATCH --job-name=JTVAE-TRA

#SBATCH --partition=gpu
#V100
#SBATCH --gres=gpu:v100:1
#P100
##SBATCH --gres=gpu:p100:1

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=200g
#SBATCH --time=119:00:00

source /home/blackst/.bashrc
hostname -s

JTVAE_GPU_PATH="/mnt/projects/ATOM/blackst/FNLGMD/workspace/development"
conda activate JTVAE-GPU-P3
export PYTHONPATH=$JTVAE_GPU_PATH

WRK="/mnt/projects/ATOM/blackst/GMD/NaturalProducts/Train"
echo $WRK
cd $WRK

VAE="$JTVAE_GPU_PATH""/test_code.py"

python -u $VAE 