#!/bin/bash

#SBATCH --job-name=JTVAE-EDF

#SBATCH --partition=norm
##SBATCH --partition=short

#SBATCH --ntasks=1
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=18
#SBATCH --mem=200g
#SBATCH --time=09:00:00

#source /home/blackst/.bashrc
#hostname -s

conda activate JTVAE-CPU-P3

EDF="./EDF.py"
DAT="<path to data>.txt"
VOC="<path to vocab file>.txt"
MOD="<path to model file>"
OUT="reconstruction_rate.out"

python -u $EDF -d $DAT        \
               -v $VOC        \
               -m $MOD        \
               -c 18          \
               -b 40          \
               >& $OUT

# Add -f above to print failed reconstructs
# Add -p above for lots of joblib.Parallel output

