#!/bin/bash

#SBATCH --job-name=GMD-Loop

#SBATCH --partition=norm

#SBATCH --ntasks=1
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100g
#SBATCH --time=09:00:00

source /home/$USER/.bashrc
hostname -s

conda activate JTVAE-CPU-P3

WRK = "/mnt/projects/ATOM/blackst/FNLGMD/source"
echo $WRK
cd $WRK

CODE="/mnt/projects/ATOM/blackst/FNLGMD/source/main.py"
CONF="/mnt/projects/ATOM/blackst/FNLGMD/source/config.yaml"

python $CODE -config $CONF