#!/bin/bash

#SBATCH --job-name=GMD-Loop

#SBATCH --partition=norm

#SBATCH --ntasks=1
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100g
#SBATCH --time=09:00:00
#SBATCH -o example.out

source /home/$USER/.bashrc
hostname -s

conda activate JTVAE-CPU-P3

WRK="/path/to/GGMD/source"
echo $WRK
cd $WRK

CODE="/path/to/GGMD/source/main.py"
CONF="/path/to/GGMD/examples/LogP_JTVAE/config.yaml"

python $CODE -config $CONF
